# Generated by Django 5.2.4 on 2025-08-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите ID сессии",
                max_length=255,
                null=True,
                verbose_name="ID сессии",
            ),
        ),
    ]
