# Generated by Django 5.2.4 on 2025-07-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Добавьте описание",
                max_length=100,
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Добавьте картинку",
                null=True,
                upload_to="lessons/picture",
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Добавьте описание",
                max_length=100,
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="name",
            field=models.CharField(
                help_text="Укажите название", max_length=30, verbose_name="Название"
            ),
        ),
    ]
